
---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table2ehpansibletest
        location: canadacentral
        tags:
          testing: testing
          delete: never
