- hosts: localhost
  connection: local
  vars:
    group: table2ehpdevopsvmvrg
    webapp_name: table2ehpdevopswebapp
    location: canadacentral
  tasks:
    - name: create rg
      azure_rm_resourcegroup:
        name: "{{group}}"
        location: "{{location}}"
    - name: Create App Svc
      azure_rm_webapp:
        resource_group: "{{group}}"
        name: "{{webapp_name}}"
        plan:
          resource_group: "{{group}}"
          name: table2ehpdevopsappplan
          is_linux: true
          sku: S1
          number_of_workers: 1
        scm_type: GitHub
        deployment_source:
          url: https://github.com/jwkidd3/slots
          branch: master
